### ISSUE TITLE
Documentation update required

### ISSUE THREAD

**Issue by jm-cook** [toringer/home-assistant-metnowcast#15]
Since core 2024.4 the nowcast integration no longer provides the forecast attribute. This is due to the fact that it has been superseded by the requirement to call `get_forecasts`. A couple of important changes are required to the documentation in order to get this working again. In `configuration.yml` it is now necessary to populate a trigger based sensor with the forecast data. Since `metnowcast` currently provides `datetime` objects, and not date strings it is also necessary to convert to iso formatted date strings. Below is my solution. I can try to send a PR but it might be some time. If another has time to fix this before I do then fine!

Note that it would also be an advantage IMO, and more compatible with other weather integrations, if the forecast included date strings and not datetime objects.

```
  - trigger:
      - platform: time_pattern
        minutes: /5
    action:
      - service: weather.get_forecasts
        target:
          entity_id: weather.met_no_nowcast_hytten
        data:
          type: hourly
        response_variable: nowcast_5min
    sensor:
      - name: nowcast
        unique_id: weather_nowcast
        state: "{{ nowcast_5min['weather.met_no_nowcast_hytten'].forecast[0].condition }}"
        attributes:
          forecast: >
            [{%- for n in nowcast_5min['weather.met_no_nowcast_hytten'].forecast  %}
               {
               {%- for k, v in n.items() %}
                 {%- if v is datetime %}
                 "{{ k }}": "{{ v.isoformat() }}",
                 {%- elif v is string %}
                 "{{ k }}": "{{ v }}",
                 {%- else %}
                 "{{ k }}": {{ v }},
                 {%- endif %}
               {%- endfor %}
               },
             {%- endfor %}]
```

The second thing you have to do in order to display a graph of the rainfall prediction is to change the yaml to use the new trigger sensor. Here is my example:

```
type: custom:chartjs-card
chart: line
data:
  datasets:
    - backgroundColor: rgb(65,105,225)
      borderWidth: 10
      fill: true
      cubicInterpolationMode: monotone
      data: >-
        ${states['sensor.nowcast'].attributes.forecast.map(fcast => ({x: (new
        Date(fcast.datetime).getTime()-new Date().getTime()), y:
        parseFloat(fcast.precipitation)}))}
  blabels: ${30}
  labels: >-
    ${states['sensor.nowcast'].attributes.forecast.map(fcast =>
    5*Math.floor((new Date(fcast.datetime).getTime()-new
    Date().getTime())/(5000*60)))}
entity_row: true
custom_options:
  showLegend: false
options:
  elements:
    point:
      radius: 0
  scales:
    x:
      max: 90
      min: 0
      display: true
      color: red
      ticks:
        callback: >-
          ${(function (val, index) {   var lval =
          parseInt(this.getLabelForValue(val));  if (lval == 0) { return 'Now';}
          else { return  lval % 30 === 0?lval:'';}   })}
        font:
          size: 18
    'y':
      beginAtZero: true
      display: true
      position: right
      grid:
        color: >-
          ${(function(context) {return context.tick.value%1
          ===0?'#aaaaaa':'#000000';})}
      ticks:
        callback: >-
          ${(function(val, index) { var lval = this.getLabelForValue(val); var
          ival = Math.round(lval); return lval % 1 === 0 ? ival : '';})}
        font:
          size: 18
      max: 3
  plugins:
    title:
      display: true
      font:
        size: 24
      text: ${states['sensor.nowcast'].state;}
```

![image](https://github.com/toringer/home-assistant-metnowcast/assets/8317651/b7d58655-6984-4fc1-8606-0c7bbfa51a7f)

**Comment by FSund** [comment]
Where do should I put the code you posted for parsing the results from `get_forecast`?

This

```yaml
  - trigger:
      - platform: time_pattern
        minutes: /5
    action:
      - service: weather.get_forecasts
        target:
          entity_id: weather.met_no_nowcast_hytten
        data:
          type: hourly
        response_variable: nowcast_5min
    sensor:
      - name: nowcast
        unique_id: weather_nowcast
        state: "{{ nowcast_5min['weather.met_no_nowcast_hytten'].forecast[0].condition }}"
        attributes:
          forecast: >
            [{%- for n in nowcast_5min['weather.met_no_nowcast_hytten'].forecast  %}
               {
               {%- for k, v in n.items() %}
                 {%- if v is datetime %}
                 "{{ k }}": "{{ v.isoformat() }}",
                 {%- elif v is string %}
                 "{{ k }}": "{{ v }}",
                 {%- else %}
                 "{{ k }}": {{ v }},
                 {%- endif %}
               {%- endfor %}
               },
             {%- endfor %}]
```
